spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: diary
      username: ${MONGO_USER_NAME}
      password: ${MONGO_USER_PASSWORD}
      authentication-database: admin
  datasource:
    url: ${MARIA_URL}
    username: ${MARIA_USER_NAME}
    password: ${MARIA_USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver