spring:
  encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
social:
  kakao:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect: ${KAKAO_REDIRECT_URL}
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      force: true

#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}