spring:
  encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
  server:
    port: 8080
    servlet:
      context-path: /
      encoding:
        charset: UTF-8
        force: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: diary
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin

    driver-class-name: org.mariadb.jdbc.Driver