spring:
  encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            client-authentication-method: POST
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  header: Authorization
  secret: ${JWT_KEY}

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ${KAKAO_CLIENT_SECRET}
#social:
#  kakao:
#    id: ${KAKAO_CLIENT_ID}
#    secret: ${KAKAO_CLIENT_SECRET}
#    redirect: ${KAKAO_REDIRECT_URL}
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      force: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}